"""add_program_groups_to_program_suggestion_students

Revision ID: 8d24ced8b0c3
Revises: migrate_to_test_rooms
Create Date: 2026-02-11 15:14:34.359592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d24ced8b0c3'
down_revision: Union[str, None] = 'migrate_to_test_rooms'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'job_recommendation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('program_suggestion_students', sa.Column('program_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('program_suggestion_students', sa.Column('alternative_jobs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('program_suggestion_students', sa.Column('alternative_program_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_suggestion_students', 'alternative_program_groups')
    op.drop_column('program_suggestion_students', 'alternative_jobs')
    op.drop_column('program_suggestion_students', 'program_groups')
    op.alter_column('players', 'job_recommendation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
