"""add_lise_tables

Revision ID: f8912e365ccd
Revises: bb118320b7fb
Create Date: 2026-02-05 17:54:37.684629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8912e365ccd'
down_revision: Union[str, None] = 'bb118320b7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lise_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_slug', sa.String(), nullable=False),
    sa.Column('yop_kodu', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('lise_id', sa.Integer(), nullable=False),
    sa.Column('yerlesen_sayisi', sa.Integer(), nullable=False),
    sa.Column('school_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lise_placements_id'), 'lise_placements', ['id'], unique=False)
    op.create_index(op.f('ix_lise_placements_lise_id'), 'lise_placements', ['lise_id'], unique=False)
    op.create_index(op.f('ix_lise_placements_university_slug'), 'lise_placements', ['university_slug'], unique=False)
    op.create_index(op.f('ix_lise_placements_year'), 'lise_placements', ['year'], unique=False)
    op.create_index(op.f('ix_lise_placements_yop_kodu'), 'lise_placements', ['yop_kodu'], unique=False)
    op.create_table('lise_placements_2025',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_university', sa.String(), nullable=False),
    sa.Column('yop_kodu', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('lise_adi', sa.String(), nullable=False),
    sa.Column('sehir', sa.String(), nullable=True),
    sa.Column('ilce', sa.String(), nullable=True),
    sa.Column('yerlesen_sayisi', sa.Integer(), nullable=False),
    sa.Column('is_ozel', sa.Boolean(), nullable=True),
    sa.Column('is_fen', sa.Boolean(), nullable=True),
    sa.Column('is_anadolu', sa.Boolean(), nullable=True),
    sa.Column('is_acik_ogretim', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lise_placements_2025_id'), 'lise_placements_2025', ['id'], unique=False)
    op.create_index(op.f('ix_lise_placements_2025_source_university'), 'lise_placements_2025', ['source_university'], unique=False)
    op.create_index(op.f('ix_lise_placements_2025_yop_kodu'), 'lise_placements_2025', ['yop_kodu'], unique=False)
    op.create_table('lises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lise_id', sa.Integer(), nullable=False),
    sa.Column('lise_adi', sa.String(), nullable=False),
    sa.Column('sehir', sa.String(), nullable=True),
    sa.Column('year_group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lises_id'), 'lises', ['id'], unique=False)
    op.create_index(op.f('ix_lises_lise_id'), 'lises', ['lise_id'], unique=True)
    op.create_table('score_ranking_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puan_turu', sa.String(), nullable=False),
    sa.Column('puan', sa.Float(), nullable=False),
    sa.Column('siralama', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_ranking_distributions_id'), 'score_ranking_distributions', ['id'], unique=False)
    op.create_index(op.f('ix_score_ranking_distributions_puan_turu'), 'score_ranking_distributions', ['puan_turu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_ranking_distributions_puan_turu'), table_name='score_ranking_distributions')
    op.drop_index(op.f('ix_score_ranking_distributions_id'), table_name='score_ranking_distributions')
    op.drop_table('score_ranking_distributions')
    op.drop_index(op.f('ix_lises_lise_id'), table_name='lises')
    op.drop_index(op.f('ix_lises_id'), table_name='lises')
    op.drop_table('lises')
    op.drop_index(op.f('ix_lise_placements_2025_yop_kodu'), table_name='lise_placements_2025')
    op.drop_index(op.f('ix_lise_placements_2025_source_university'), table_name='lise_placements_2025')
    op.drop_index(op.f('ix_lise_placements_2025_id'), table_name='lise_placements_2025')
    op.drop_table('lise_placements_2025')
    op.drop_index(op.f('ix_lise_placements_yop_kodu'), table_name='lise_placements')
    op.drop_index(op.f('ix_lise_placements_year'), table_name='lise_placements')
    op.drop_index(op.f('ix_lise_placements_university_slug'), table_name='lise_placements')
    op.drop_index(op.f('ix_lise_placements_lise_id'), table_name='lise_placements')
    op.drop_index(op.f('ix_lise_placements_id'), table_name='lise_placements')
    op.drop_table('lise_placements')
    # ### end Alembic commands ###
