"""add_tercih_stats_tables

Revision ID: bb118320b7fb
Revises: cd3b14f93cef
Create Date: 2026-02-05 15:44:46.120458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb118320b7fb'
down_revision: Union[str, None] = 'cd3b14f93cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yop_kodu', sa.String(length=20), nullable=True),
    sa.Column('is_english', sa.Boolean(), nullable=True),
    sa.Column('scholarship_pct', sa.Float(), nullable=True),
    sa.Column('full_price_2024', sa.Float(), nullable=True),
    sa.Column('full_price_2025', sa.Float(), nullable=True),
    sa.Column('discounted_price_2024', sa.Float(), nullable=True),
    sa.Column('discounted_price_2025', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['yop_kodu'], ['programs.yop_kodu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_prices_id'), 'program_prices', ['id'], unique=False)
    op.create_index(op.f('ix_program_prices_yop_kodu'), 'program_prices', ['yop_kodu'], unique=False)
    op.create_table('tercih_istatistikleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yop_kodu', sa.String(length=20), nullable=True),
    sa.Column('bir_kontenjana_talip_olan_aday_sayisi_2022', sa.Float(), nullable=True),
    sa.Column('bir_kontenjana_talip_olan_aday_sayisi_2023', sa.Float(), nullable=True),
    sa.Column('bir_kontenjana_talip_olan_aday_sayisi_2024', sa.Float(), nullable=True),
    sa.Column('bir_kontenjana_talip_olan_aday_sayisi_2025', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_sayisi_2022', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_sayisi_2023', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_sayisi_2024', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_sayisi_2025', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_orani_2022', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_orani_2023', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_orani_2024', sa.Float(), nullable=True),
    sa.Column('ilk_uc_sirada_tercih_eden_orani_2025', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_sayisi_2022', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_sayisi_2023', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_sayisi_2024', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_sayisi_2025', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_orani_2022', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_orani_2023', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_orani_2024', sa.Float(), nullable=True),
    sa.Column('ilk_uc_tercih_olarak_yerlesen_orani_2025', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['yop_kodu'], ['programs.yop_kodu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tercih_istatistikleri_id'), 'tercih_istatistikleri', ['id'], unique=False)
    op.create_index(op.f('ix_tercih_istatistikleri_yop_kodu'), 'tercih_istatistikleri', ['yop_kodu'], unique=True)
    op.create_table('tercih_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_university', sa.String(length=100), nullable=True),
    sa.Column('yop_kodu', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('preference_type', sa.String(length=20), nullable=True),
    sa.Column('preferred_item', sa.String(length=255), nullable=True),
    sa.Column('tercih_sayisi', sa.Integer(), nullable=True),
    sa.Column('university_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['yop_kodu'], ['programs.yop_kodu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tercih_preferences_id'), 'tercih_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_tercih_preferences_preference_type'), 'tercih_preferences', ['preference_type'], unique=False)
    op.create_index(op.f('ix_tercih_preferences_source_university'), 'tercih_preferences', ['source_university'], unique=False)
    op.create_index(op.f('ix_tercih_preferences_year'), 'tercih_preferences', ['year'], unique=False)
    op.create_index(op.f('ix_tercih_preferences_yop_kodu'), 'tercih_preferences', ['yop_kodu'], unique=False)
    op.create_table('tercih_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yop_kodu', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ortalama_tercih_edilme_sirasi', sa.Float(), nullable=True),
    sa.Column('ortalama_yerlesen_tercih_sirasi', sa.Float(), nullable=True),
    sa.Column('marka_etkinlik_degeri', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['yop_kodu'], ['programs.yop_kodu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tercih_stats_id'), 'tercih_stats', ['id'], unique=False)
    op.create_index(op.f('ix_tercih_stats_year'), 'tercih_stats', ['year'], unique=False)
    op.create_index(op.f('ix_tercih_stats_yop_kodu'), 'tercih_stats', ['yop_kodu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tercih_stats_yop_kodu'), table_name='tercih_stats')
    op.drop_index(op.f('ix_tercih_stats_year'), table_name='tercih_stats')
    op.drop_index(op.f('ix_tercih_stats_id'), table_name='tercih_stats')
    op.drop_table('tercih_stats')
    op.drop_index(op.f('ix_tercih_preferences_yop_kodu'), table_name='tercih_preferences')
    op.drop_index(op.f('ix_tercih_preferences_year'), table_name='tercih_preferences')
    op.drop_index(op.f('ix_tercih_preferences_source_university'), table_name='tercih_preferences')
    op.drop_index(op.f('ix_tercih_preferences_preference_type'), table_name='tercih_preferences')
    op.drop_index(op.f('ix_tercih_preferences_id'), table_name='tercih_preferences')
    op.drop_table('tercih_preferences')
    op.drop_index(op.f('ix_tercih_istatistikleri_yop_kodu'), table_name='tercih_istatistikleri')
    op.drop_index(op.f('ix_tercih_istatistikleri_id'), table_name='tercih_istatistikleri')
    op.drop_table('tercih_istatistikleri')
    op.drop_index(op.f('ix_program_prices_yop_kodu'), table_name='program_prices')
    op.drop_index(op.f('ix_program_prices_id'), table_name='program_prices')
    op.drop_table('program_prices')
    # ### end Alembic commands ###
