"""add_full_name_and_student_number_to_participants

Revision ID: ef862fdb2118
Revises: 2026_02_06_006
Create Date: 2026-02-06 21:59:30.204068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef862fdb2118'
down_revision: Union[str, None] = '2026_02_06_006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dissonance_test_participants', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('dissonance_test_participants', sa.Column('student_number', sa.String(length=50), nullable=True))
    op.add_column('personality_test_participants', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('personality_test_participants', sa.Column('student_number', sa.String(length=50), nullable=True))
    op.drop_index('ix_test_rooms_is_active', table_name='test_rooms')
    op.create_index(op.f('ix_test_rooms_deleted_at'), 'test_rooms', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_rooms_deleted_at'), table_name='test_rooms')
    op.create_index('ix_test_rooms_is_active', 'test_rooms', ['is_active'], unique=False)
    op.drop_column('personality_test_participants', 'student_number')
    op.drop_column('personality_test_participants', 'full_name')
    op.drop_column('dissonance_test_participants', 'student_number')
    op.drop_column('dissonance_test_participants', 'full_name')
    # ### end Alembic commands ###
