"""add_device_fingerprint_to_program_suggestion_students

Revision ID: 4be0b425c18d
Revises: 80c52e849043
Create Date: 2026-02-11 22:14:52.604789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be0b425c18d'
down_revision: Union[str, None] = '80c52e849043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_suggestion_students', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_program_suggestion_students_device_fingerprint'), 'program_suggestion_students', ['device_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_suggestion_students_device_fingerprint'), table_name='program_suggestion_students')
    op.drop_column('program_suggestion_students', 'device_fingerprint')
    # ### end Alembic commands ###
