"""add_test_room_id_and_device_fingerprint_to_dissonance_test

Revision ID: 6b1cf37ae5d9
Revises: ef862fdb2118
Create Date: 2026-02-07 12:46:52.041465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1cf37ae5d9'
down_revision: Union[str, None] = 'ef862fdb2118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dissonance_test_participants', sa.Column('test_room_id', sa.Integer(), nullable=True))
    op.add_column('dissonance_test_participants', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('dissonance_test_participants', sa.Column('has_completed', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dissonance_test_participants_device_fingerprint'), 'dissonance_test_participants', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_dissonance_test_participants_test_room_id'), 'dissonance_test_participants', ['test_room_id'], unique=False)
    op.create_foreign_key(None, 'dissonance_test_participants', 'test_rooms', ['test_room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dissonance_test_participants', type_='foreignkey')
    op.drop_index(op.f('ix_dissonance_test_participants_test_room_id'), table_name='dissonance_test_participants')
    op.drop_index(op.f('ix_dissonance_test_participants_device_fingerprint'), table_name='dissonance_test_participants')
    op.drop_column('dissonance_test_participants', 'has_completed')
    op.drop_column('dissonance_test_participants', 'device_fingerprint')
    op.drop_column('dissonance_test_participants', 'test_room_id')
    # ### end Alembic commands ###
