"""fix_lise_unique_constraint

Revision ID: db19c00f3c56
Revises: f8912e365ccd
Create Date: 2026-02-05 17:56:12.559607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db19c00f3c56'
down_revision: Union[str, None] = 'f8912e365ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lises_lise_id', table_name='lises')
    op.create_index(op.f('ix_lises_lise_id'), 'lises', ['lise_id'], unique=False)
    op.create_unique_constraint('uq_lise_id_year_group', 'lises', ['lise_id', 'year_group'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lise_id_year_group', 'lises', type_='unique')
    op.drop_index(op.f('ix_lises_lise_id'), table_name='lises')
    op.create_index('ix_lises_lise_id', 'lises', ['lise_id'], unique=True)
    # ### end Alembic commands ###
