"""add_universities_programs_tables

Revision ID: cd3b14f93cef
Revises: fff0fd95ec84
Create Date: 2026-02-05 13:05:33.445050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3b14f93cef'
down_revision: Union[str, None] = 'fff0fd95ec84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('university_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_city'), 'universities', ['city'], unique=False)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yop_kodu', sa.String(length=20), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('scholarship', sa.String(length=100), nullable=True),
    sa.Column('puan_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_index(op.f('ix_programs_puan_type'), 'programs', ['puan_type'], unique=False)
    op.create_index(op.f('ix_programs_university_id'), 'programs', ['university_id'], unique=False)
    op.create_index('ix_programs_university_puan', 'programs', ['university_id', 'puan_type'], unique=False)
    op.create_index(op.f('ix_programs_yop_kodu'), 'programs', ['yop_kodu'], unique=True)
    op.create_table('program_yearly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('yerlesen', sa.Integer(), nullable=True),
    sa.Column('taban_puan', sa.String(length=50), nullable=True),
    sa.Column('tavan_puan', sa.String(length=50), nullable=True),
    sa.Column('tavan_basari_sirasi', sa.String(length=50), nullable=True),
    sa.Column('taban_basari_sirasi', sa.Integer(), nullable=True),
    sa.Column('has_data', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'year', name='uq_program_year')
    )
    op.create_index(op.f('ix_program_yearly_stats_id'), 'program_yearly_stats', ['id'], unique=False)
    op.create_index(op.f('ix_program_yearly_stats_program_id'), 'program_yearly_stats', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_yearly_stats_year'), 'program_yearly_stats', ['year'], unique=False)
    op.create_index('ix_program_yearly_stats_year_tbs', 'program_yearly_stats', ['year', 'taban_basari_sirasi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_yearly_stats_year_tbs', table_name='program_yearly_stats')
    op.drop_index(op.f('ix_program_yearly_stats_year'), table_name='program_yearly_stats')
    op.drop_index(op.f('ix_program_yearly_stats_program_id'), table_name='program_yearly_stats')
    op.drop_index(op.f('ix_program_yearly_stats_id'), table_name='program_yearly_stats')
    op.drop_table('program_yearly_stats')
    op.drop_index(op.f('ix_programs_yop_kodu'), table_name='programs')
    op.drop_index('ix_programs_university_puan', table_name='programs')
    op.drop_index(op.f('ix_programs_university_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_puan_type'), table_name='programs')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_city'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
