"""Add session model

Revision ID: 5e82002f54c5
Revises: 39830dfd53cb
Create Date: 2024-07-31 12:20:56.487551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '5e82002f54c5'
down_revision: Union[str, None] = '39830dfd53cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('room_id', sa.INTEGER(), nullable=False),
        sa.Column('player_ids', sa.Text(), nullable=False), 
        sa.Column('status', sa.VARCHAR(), nullable=True, server_default='pending'),
        sa.Column('results', JSONB, nullable=True),
        sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='sessions_room_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###