"""add_university_to_users

Revision ID: 705261ddbf64
Revises: 18be8e68456a
Create Date: 2026-02-01 17:45:15.424312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705261ddbf64'
down_revision: Union[str, None] = '18be8e68456a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university', sa.String(length=20), nullable=False, server_default='halic'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'university')
    # ### end Alembic commands ###
