"""Add session_id to games

Revision ID: 84dfed329760
Revises: 5e82002f54c5
Create Date: 2024-08-01 13:21:53.650077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84dfed329760'
down_revision: Union[str, None] = '5e82002f54c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'session_id')
    # ### end Alembic commands ###
