from app.dependencies.auth import (
    AdminUser,
    CurrentActiveUser,
    CurrentUser,
    DbSession,
    OptionalUser,
    TeacherOrAdmin,
    UniversityKey,
    UserRole,
    get_current_active_user,
    get_current_user,
    get_current_user_optional,
    get_db,
    is_admin,
    is_teacher_or_admin,
    oauth2_scheme,
    require_admin,
    require_role,
    require_same_university,
    require_teacher_or_admin,
    require_university,
    require_user_ownership,
)
from app.dependencies.participant import (
    CurrentParticipant,
    CurrentPlayer,
    CurrentProgramStudent,
    CurrentTestParticipant,
    get_current_participant,
    get_player,
    get_program_student,
    get_test_participant,
    verify_participant_ownership,
)

__all__ = [
    # Auth dependencies
    "get_db",
    "DbSession",
    "get_current_user",
    "get_current_active_user",
    "get_current_user_optional",
    "CurrentUser",
    "CurrentActiveUser",
    "OptionalUser",
    "require_user_ownership",
    "oauth2_scheme",
    # role based dependencies
    "require_role",
    "require_admin",
    "require_teacher_or_admin",
    "require_university",
    "require_same_university",
    "is_admin",
    "is_teacher_or_admin",
    "AdminUser",
    "TeacherOrAdmin",
    "UserRole",
    "UniversityKey",
    # student dependencies
    "get_current_participant",
    "get_player",
    "get_test_participant",
    "get_program_student",
    "CurrentParticipant",
    "CurrentPlayer",
    "CurrentTestParticipant",
    "CurrentProgramStudent",
    "verify_participant_ownership",
]
